# Generated by Django 4.0.5 on 2022-08-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=150)),
                ('MRN', models.CharField(max_length=10)),
                ('Gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('DOB', models.DateField()),
                ('HospitalName', models.CharField(max_length=200)),
                ('LastUpdatedBy', models.CharField(max_length=120)),
                ('LastUpdatedTime', models.DateTimeField(auto_now=True)),
                ('NoteId', models.CharField(max_length=10)),
                ('NoteDateTime', models.DateTimeField(auto_now_add=True)),
                ('Prescription', models.TextField(max_length=600)),
            ],
        ),
    ]
