# Generated by Django 4.0.5 on 2022-08-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='LastUpdatedBy',
            field=models.CharField(max_length=120),
        ),
    ]
