# Generated by Django 4.0.5 on 2022-08-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientData', '0002_alter_patientdata_lastupdatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='Prescription',
            field=models.TextField(max_length=1200),
        ),
    ]
